ZONA_MAPPING = {
    # Zona Sul
    'Botafogo': 'Zona Sul',
    'Catete': 'Zona Sul',
    'Copacabana': 'Zona Sul',
    'Cosme Velho': 'Zona Sul',
    'Flamengo': 'Zona Sul',
    'Gávea': 'Zona Sul',
    'Glória': 'Zona Sul',
    'Humaitá': 'Zona Sul',
    'Ipanema': 'Zona Sul',
    'Jardim Botânico': 'Zona Sul',
    'Lagoa': 'Zona Sul',
    'Laranjeiras': 'Zona Sul',
    'Leblon': 'Zona Sul',
    'Leme': 'Zona Sul',
    'Rocinha': 'Zona Sul',
    'São Conrado': 'Zona Sul',
    'Urca': 'Zona Sul',
    'Vidigal': 'Zona Sul',

    # Zona Norte
    'Abolição': 'Zona Norte',
    'Acari': 'Zona Norte',
    'Água Santa': 'Zona Norte',
    'Anchieta': 'Zona Norte',
    'Barros Filho': 'Zona Norte',
    'Bento Ribeiro': 'Zona Norte',
    'Bonsucesso': 'Zona Norte',
    'Brás de Pina': 'Zona Norte',
    'Cachambi': 'Zona Norte',
    'Campinho': 'Zona Norte',
    'Cascadura': 'Zona Norte',
    'Cavalcanti': 'Zona Norte',
    'Coelho Neto': 'Zona Norte',
    'Colégio': 'Zona Norte',
    'Complexo do Alemão': 'Zona Norte',
    'Cordovil': 'Zona Norte',
    'Costa Barros': 'Zona Norte',
    'Del Castilho': 'Zona Norte',
    'Encantado': 'Zona Norte',
    'Engenheiro Leal': 'Zona Norte',
    'Engenho da Rainha': 'Zona Norte',
    'Engenho de Dentro': 'Zona Norte',
    'Engenho Novo': 'Zona Norte',
    'Guadalupe': 'Zona Norte',
    'Higienópolis': 'Zona Norte',
    'Honório Gurgel': 'Zona Norte',
    'Inhaúma': 'Zona Norte',
    'Irajá': 'Zona Norte',
    'Jacaré': 'Zona Norte',
    'Jacarezinho': 'Zona Norte',
    'Jardim América': 'Zona Norte',
    'Lins de Vasconcelos': 'Zona Norte',
    'Madureira': 'Zona Norte',
    'Manguinhos': 'Zona Norte',
    'Maré': 'Zona Norte',
    'Marechal Hermes': 'Zona Norte',
    'Maria da Graça': 'Zona Norte',
    'Méier': 'Zona Norte',
    'Olaria': 'Zona Norte',
    'Oswaldo Cruz': 'Zona Norte',
    'Parada de Lucas': 'Zona Norte',
    'Parque Anchieta': 'Zona Norte',
    'Parque Colúmbia': 'Zona Norte',
    'Pavuna': 'Zona Norte',
    'Penha': 'Zona Norte',
    'Penha Circular': 'Zona Norte',
    'Piedade': 'Zona Norte',
    'Pilares': 'Zona Norte',
    'Quintino Bocaiuva': 'Zona Norte',
    'Ramos': 'Zona Norte',
    'Riachuelo': 'Zona Norte',
    'Ricardo de Albuquerque': 'Zona Norte',
    'Rocha': 'Zona Norte',
    'Rocha Miranda': 'Zona Norte',
    'Sampaio': 'Zona Norte',
    'São Francisco Xavier': 'Zona Norte',
    'Todos os Santos': 'Zona Norte',
    'Tomás Coelho': 'Zona Norte',
    'Turiaçu': 'Zona Norte',
    'Vaz Lobo': 'Zona Norte',
    'Vicente de Carvalho': 'Zona Norte',
    'Vigário Geral': 'Zona Norte',
    'Vila da Penha': 'Zona Norte',
    'Vila Kosmos': 'Zona Norte',
    'Vista Alegre': 'Zona Norte',

    # Zona Oeste
    'Anil': 'Zona Oeste',
    'Bangu': 'Zona Oeste',
    'Barra da Tijuca': 'Zona Oeste',
    'Barra Olímpica': 'Zona Oeste',
    'Camorim': 'Zona Oeste',
    'Campo dos Afonsos': 'Zona Oeste',
    'Campo Grande': 'Zona Oeste',
    'Cidade de Deus': 'Zona Oeste',
    'Cosmos': 'Zona Oeste',
    'Curicica': 'Zona Oeste',
    'Deodoro': 'Zona Oeste',
    'Gardênia Azul': 'Zona Oeste',
    'Gericinó': 'Zona Oeste',
    'Grumari': 'Zona Oeste',
    'Guaratiba': 'Zona Oeste',
    'Ilha de Guaratiba': 'Zona Oeste',
    'Inhoaíba': 'Zona Oeste',
    'Jacarepaguá': 'Zona Oeste',
    'Jabour': 'Zona Oeste',
    'Jardim Sulacap': 'Zona Oeste',
    'Joá': 'Zona Oeste',
    'Magalhães Bastos': 'Zona Oeste',
    'Padre Miguel': 'Zona Oeste',
    'Paciência': 'Zona Oeste',
    'Pedra de Guaratiba': 'Zona Oeste',
    'Pechincha': 'Zona Oeste',
    'Praça Seca': 'Zona Oeste',
    'Realengo': 'Zona Oeste',
    'Recreio dos Bandeirantes': 'Zona Oeste',
    'Santa Cruz': 'Zona Oeste',
    'Santíssimo': 'Zona Oeste',
    'Senador Camará': 'Zona Oeste',
    'Senador Vasconcelos': 'Zona Oeste',
    'Sepetiba': 'Zona Oeste',
    'Tanque': 'Zona Oeste',
    'Taquara': 'Zona Oeste',
    'Vargem Grande': 'Zona Oeste',
    'Vargem Pequena': 'Zona Oeste',
    'Vila Kennedy': 'Zona Oeste',
    'Vila Militar': 'Zona Oeste',
    'Vila Valqueire': 'Zona Oeste',

    # Zona Central
    'Bairro Imperial de São Cristóvão': 'Zona Central',
    'Benfica': 'Zona Central',
    'Caju': 'Zona Central',
    'Catumbi': 'Zona Central',
    'Centro': 'Zona Central',
    'Cidade Nova': 'Zona Central',
    'Estácio': 'Zona Central',
    'Gamboa': 'Zona Central',
    'Lapa': 'Zona Central',
    'Mangueira': 'Zona Central',
    'Paquetá': 'Zona Central',
    'Rio Comprido': 'Zona Central',
    'Santa Teresa': 'Zona Central',
    'Santo Cristo': 'Zona Central',
    'Saúde': 'Zona Central',
    'Vasco da Gama': 'Zona Central',
}

TIPO_EVENTO_MAPPING = {
    ('ACCIDENT', 'MINOR'): 'Acidente pequeno',
    ('ACCIDENT', 'MAJOR'): 'Acidente grave',
    ('ACCIDENT', ''): 'Acidente não especificado',
    ('HAZARD', 'WEATHER'): 'Perigo climático',
    ("HAZARD", "HAZARD_ON_ROAD_POT_HOLE"): 'Buraco na estrada',
    ("HAZARD", "HAZARD_ON_SHOULDER_CAR_STOPPED"): 'Carro Parado na pista',
    ('ROAD_CLOSED', 'ROAD_CLOSED_EVENT'): 'Estrada fechada',
    ('JAM', 'JAM_HEAVY_TRAFFIC'): 'Engarrafamento grave',
    ('JAM', 'JAM_MODERATE_TRAFFIC'): 'Engarrafamento moderado',
    ('JAM', 'JAM_LIGHT_TRAFFIC'): 'Engarrafamento leve',
    ('JAM', 'JAM_STAND_STILL_TRAFFIC'): 'Trânsito parado',
    ('JAM', ''): 'Engarrafamento',
    ('POLICE', ''): 'Polícia',
    ('CONSTRUCTION', ''): 'Construção',
    ('WEATHER', 'FOG'): 'Névoa',
    ('WEATHER', 'HAIL'): 'Granizo',
    ('WEATHER', 'HEAVY_RAIN'): 'Chuva forte',
    ('WEATHER', 'SNOW'): 'Neve',
    ('WEATHER', 'ICE'): 'Gelo',
    ('WEATHER', 'FLOOD'): 'Alagamento'




}
